/*El layout representa las rutas de nuestra aplicacion*/
import Link from "next/link"
/*Creación de rutas*/
const links = [{
  label : "Home",
  route : "./"
},{
  label : "About",
  route : "./about"
},{
  label : "Post",
  route : "./post"
}
]
export const metadata = {
  title: 'Aprendiendo Next JS',
  description: 'Generated by Next.js',
}

/*Funcion de Rutas*/
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <header>
          <nav>
            {links.map(({label,route})=>(
              <li key={route}>
                <Link href={route}>
                  {label}
                </Link>
              </li>
            ))}
          </nav>
        </header>
        {children}
      </body>
    </html>
  )
}
